### PR TITLE
feat: Add completion items previews and title inserting

### LINKED ISSUE #117: Feature Request: autocomplete with h1 title
When linking `02-started.md` document in `01-intro.md` document, it would be greate to be able to bring the h1 title of document `02-started.md`.

e.g. 
`01-intro.md`
```markdown
# Intro
This is some text, link [[02-started|Let's started]]
```
`02-started.md`
```markdown
# Let's started
Do something.
```

### PR DESCRIPTION
**Pull request by d7sd6u**
This PR adds completion items previews for notes and images like on this picture: 
Also it adds automatic title inserting and fixes #117

### CODE REVIEW

**Comment by svsool** [comment]
Hi,

Thanks for PRs!

I noticed 3 PRs opened and shared changes between them. Would it be possible to change PRs' so that there are no code overlaps? This would ease review a lot.

This week I'm on holidays 🌴 , so might be away a lot.

**Comment by d7sd6u** [comment]
Hello. I can split the first PR, but not the third with the second, because it depends on the completion items cache.

By the way, I decided to completely redo the cache, and as a result, in my personal branch, I completely changed all the main internal architecture related to links. The new cache adds new abstractions that make it much easier to implement any features.

When I finish working on this branch, it will turn out to be a very large PR, will you review it at all or will I have to create and maintain my own fork? So far I have reached feature-parity with master-branch and all E2E tests pass, but I still need to write unit tests and documentation for all new internal functions. If you like, I can push my working branch to my repository so you can take a look at the number of changes, but please beware, that it is still very much work in progress.

P.S. Naturally, this future PR will make #441, #439, #437 obsolete, so if you don't mind merging the future PR, it may be better not to waste time on #441, #439, #437 and close them.

**Comment by svsool** [comment]
Probably bigger PR would be more preferable to review in this case, even though harder. At least comments can be kept in sync with the code vs being scattered across PRs.

**Comment by d7sd6u** [comment]
Ok. Then I close these PRs.

**Pull request closed without merging**
